import supabase from './db-client.js';
import { allowed } from './rate-limit.js';
const stages=['Order Placed','Payment Confirmed','Processing','Ready','Out for Delivery','Delivered'];
const clean=(v,n=200)=>String(v??'').trim().slice(0,n);
async function currentUser(req){const token=req.headers.authorization?.replace('Bearer ','');if(!token)return null;const {data}=await supabase.auth.getUser(token);return data?.user||null}
export default async function handler(req,res){res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS')return res.status(204).end();try{
 const user=await currentUser(req);
 if(req.method==='GET'){const code=clean(req.query.code,40);const email=clean(req.query.email,150).toLowerCase();if(!user && !(code&&email))return res.status(401).json({error:'Sign in or enter order number and email to track'});let query=supabase.from('orders').select('*').order('id',{ascending:false});if(code&&email)query=query.eq('order_number',code).eq('email',email);else query=query.eq('user_id',user.id);const {data,error}=await query;if(error)throw error;return res.status(200).json(data)}
 if(req.method==='POST'){if(!allowed(req,'orders',5))return res.status(429).json({error:'Too many requests. Please try again shortly.'});const b=req.body||{};const name=clean(b.name,120),email=clean(b.email,150).toLowerCase(),phone=clean(b.phone,40),town=clean(b.town,100),address=clean(b.address,300),county=clean(b.county,100);if(!name||!/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(email)||!phone)return res.status(400).json({error:'Name, valid email and phone are required'});if(b.payment_method!=='pay_on_delivery')return res.status(503).json({error:'Online M-Pesa and card payments are not connected yet. Please choose Pay on delivery / pickup.'});if(!Array.isArray(b.items)||!b.items.length||b.items.length>40)return res.status(400).json({error:'Cart is empty or too large'});
 const ids=[...new Set(b.items.map(i=>Number(i.id)))];if(ids.length!==b.items.length||ids.some(i=>!Number.isInteger(i)||i<=0))return res.status(400).json({error:'Invalid or duplicate cart items'});const {data:products,error:pe}=await supabase.from('products').select('*').in('id',ids).eq('active',true);if(pe)throw pe;const items=[];let subtotal=0;for(const item of b.items){const product=products.find(p=>p.id===Number(item.id));const quantity=Number(item.quantity);if(!product||!Number.isInteger(quantity)||quantity<1||quantity>50||quantity>product.stock)return res.status(400).json({error:`Item unavailable or insufficient stock: ${product?.name||'product'}`});items.push({product_id:product.id,product_name:product.name,quantity,unit_price:Number(product.price)});subtotal+=Number(product.price)*quantity}
 let fee=0,zoneName='Farm pickup';if(b.delivery_method==='delivery'){if(!county||!town||!address)return res.status(400).json({error:'Delivery address, county and town are required'});const {data:zone,error:ze}=await supabase.from('delivery_zones').select('*').eq('county',county).eq('active',true).single();if(ze||!zone)return res.status(400).json({error:'Delivery is not yet configured for that county'});fee=Number(zone.fee);zoneName=zone.county}else if(b.delivery_method!=='pickup')return res.status(400).json({error:'Choose pickup or delivery'});
 const orderNumber=`VP-${Date.now().toString(36).toUpperCase()}-${crypto.randomUUID().slice(0,8).toUpperCase()}`;const {data:order,error:oe}=await supabase.from('orders').insert({order_number:orderNumber,user_id:user?.id||null,name,email,phone,county:zoneName,town:town||'',address:address||'',instructions:clean(b.instructions,500),delivery_method:b.delivery_method,delivery_fee:fee,subtotal,total:subtotal+fee,payment_method:'pay_on_delivery',payment_status:'unpaid',status:stages[0]}).select('*').single();if(oe)throw oe;const {error:ie}=await supabase.from('order_items').insert(items.map(i=>({...i,order_id:order.id})));if(ie){await supabase.from('orders').delete().eq('id',order.id);throw ie}return res.status(201).json(order)}
 return res.status(405).json({error:'Method not allowed'})
 }catch(err){console.error('orders error',err);return res.status(500).json({error:'Unable to process order. Please try again.'})}}
