import supabase from './db-client.js';
async function userFrom(req){const token=req.headers.authorization?.replace('Bearer ','');if(!token)return null;const {data}=await supabase.auth.getUser(token);return data?.user||null}
export default async function handler(req,res){
 res.setHeader('Access-Control-Allow-Origin','*');res.setHeader('Access-Control-Allow-Methods','GET, POST, PUT, DELETE, OPTIONS');res.setHeader('Access-Control-Allow-Headers','Content-Type, Authorization');if(req.method==='OPTIONS')return res.status(204).end();
 try{const user=await userFrom(req);if(!user)return res.status(401).json({error:'Sign in to continue'});const type=String(req.query.type||'profile');if(!['profile','wishlist','addresses'].includes(type))return res.status(400).json({error:'Invalid account section'});const table=type==='wishlist'?'wishlists':type==='addresses'?'addresses':'profiles';
 if(req.method==='GET'){const {data,error}=await supabase.from(table).select('*').eq('user_id',user.id).order('id',{ascending:false});if(error)throw error;return res.status(200).json(data)}
 if(req.method==='POST'&&type==='wishlist'){const id=Number(req.body?.product_id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid product'});const {data:existing}=await supabase.from('wishlists').select('*').eq('user_id',user.id).eq('product_id',id).maybeSingle();if(existing)return res.status(200).json(existing);const {data,error}=await supabase.from('wishlists').insert({user_id:user.id,product_id:id}).select('*').single();if(error)throw error;return res.status(201).json(data)}
 if(req.method==='POST'&&type==='addresses'){const b=req.body||{};if(!String(b.county||'').trim()||!String(b.town||'').trim()||!String(b.address||'').trim())return res.status(400).json({error:'County, town and address are required'});const {data,error}=await supabase.from('addresses').insert({user_id:user.id,label:String(b.label||'Address').slice(0,80),county:String(b.county).slice(0,100),town:String(b.town).slice(0,100),address:String(b.address).slice(0,300)}).select('*').single();if(error)throw error;return res.status(201).json(data)}
 if(req.method==='PUT'&&type==='profile'){const values={full_name:String(req.body?.full_name||'').slice(0,120),phone:String(req.body?.phone||'').slice(0,40)};const {data:existing,error:lookupError}=await supabase.from('profiles').select('id').eq('user_id',user.id).maybeSingle();if(lookupError)throw lookupError;const query=existing?supabase.from('profiles').update(values).eq('id',existing.id).eq('user_id',user.id):supabase.from('profiles').insert({user_id:user.id,...values,role:'customer'});const {data,error}=await query.select('*').single();if(error)throw error;return res.status(200).json(data)}
 if(req.method==='DELETE'&&['wishlist','addresses'].includes(type)){const id=Number(req.body?.id);if(!Number.isInteger(id)||id<1)return res.status(400).json({error:'Invalid ID'});const {error}=await supabase.from(table).delete().eq('id',id).eq('user_id',user.id);if(error)throw error;return res.status(200).json({ok:true})}return res.status(405).json({error:'Method not allowed'})
 }catch(err){console.error('account error',err);return res.status(500).json({error:'Account request failed'})}
}
